### ISSUE TITLE
Feature: Tracking

### ISSUE THREAD

**Issue by waylapwong** [minfactory/minpenandpaper#14]
### User Story

> As a user, I want a tracking tool implemented within the application so that the developers can anaylze user's behaviour to derive improvements from it.

### Acceptance Criteria

- [ ] Google Analytics platform (account, settings etc.) is set up
- [ ] Google Analytics is implemented
- [ ] Tracking in production is enabled

### Branch

`feature/tracking`
